version: "3"
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=rokas
      - MONGO_PASSWORD=rokas
      - SESSION_SECRET=secret
    command: yarn dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rokas
      - MONGO_INITDB_ROOT_PASSWORD=rokas
